config/routes.rb
Rails.application.routes.draw do
  root "products#index" 
  resources :products
   
  get 'home/index'
  get 'home/detail'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/maker.rb
class Maker < ApplicationRecord
    has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :maker
  has_many :product_details, -> { order('sale_date DESC') }
  
  def recent_product_detail
    product_details.first
  end
  
end

app/models/product_detail.rb
class ProductDetail < ApplicationRecord
    belongs_to :product
    
  def priceperweight
    price.to_f / net_weight
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.joins(:product_details).select('products.*, product_details.*')
  end

  def show
    @product = Product.find params[:id]
  end

  def new
    @product = Product.new
    @makers = Maker.all
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to products_path
  end

  def product_params
    params.require(:product).permit(:maker_id, :name, :net_weight, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/detail.html.erb
<h2>詳細ページ</h2>

app/views/home/index.html.erb
<h1>shrinkflation TOP</h1>

<section class="bg-light text-center py-5">
  <h2 class="mb-5">一覧(仮)</h2>
  <div class="container">
    <table class="table table-sm table-hover table-striped table-dark">
<thead>
<tr>
  <th scope="col">メーカー</th>
  <th scope="col">商品名</th>
　　　<th scope="col">内容量</th>
  <th scope="col">価格</th>
  <th scope="col">グラム単価</th>
　　　<th scope="col">実質値上げ率(対3年前比)</th>
</tr>
</thead>
<tbody>
<tr>
  <th scope="row">カルビー</th>
  <td>ポテトチップス</td>
　　　<td>60g</td>
  <td>100円</td>
　　　<td>1.67円/g
  <td>###</td>
</tr>
<tr>
  <th scope="row">カルビー</th>
  <td>ポテトチップス BIGBAG</td>
　　　<td>170g</td>
　　　<td>215円</td>
  <td>1.26円/g</td>
  <td>###</td>
</tr>
<tr>
  <th scope="row">カルビー</th>
  <td>堅あげポテト</td>
　　　<td>65g</td>
　　　<td>100円</td>
　　　<td>1.54円/g</td>
  <td>###</td>
</tr>
</tbody>
</table>

<table class="table table-sm table-hover table-striped table-dark">
<thead>
<tr>
<th scope="col">メーカー</th>
<th scope="col">商品名</th>
　　　<th scope="col">内容量</th>
<th scope="col">価格</th>
<th scope="col">グラム単価</th>
　　　<th scope="col">実質値上げ率(対3年前比)</th>
</tr>
</thead>
<tbody>
<tr>
<th scope="row">亀田製菓</th>
<td>亀田の柿の種 袋詰</td>
　　　<td>200g</td>
<td>198円</td>
　　　<td>円/g
<td>###</td>
</tr>
<tr>
<th scope="row">亀田製菓</th>
<td>手塩屋</td>
　　　<td>9枚</td>
　　　<td>175円</td>
<td>円/枚</td>
<td>###</td>
</tr>
<tr>
<th scope="row">亀田製菓</th>
<td>サラダうす焼</td>
　　　<td>85g</td>
　　　<td>130円</td>
　　　<td>円/g</td>
<td>###</td>
</tr>
</tbody>
</table>
</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shrinkflation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- BootstrapのCSS読み込み -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery読み込み -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- BootstrapのJS読み込み -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/create.html.erb
<%= link_to "トップページ", root_path %>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>dbからデータを読み込んで一覧表示するページ</p>

<%= link_to "新規登録", new_product_path %>

<p>
  <% @products.each do |product| %>
  <% end %>
</p>


<section class="bg-light text-center py-5">
  <h2 class="mb-5">一覧(仮)</h2>
  <div class="container">
    <table class="table table-sm table-hover table-striped table-dark">
<thead>
<tr>
  <th scope="col">メーカー</th>
  <th scope="col">商品名</th>
  <th scope="col">年月</th>
  <th scope="col">内容量</th>
  <th scope="col">価格</th>
  <th scope="col">グラム単価</th>
      <th scope="col">実質値上げ率（倍）</th>
</tr>
</thead>
<tbody>
<%
  @products.each do |product|
    rowspan = product.product_details.count
%>
<tr>
  <th scope="row" rowspan="<%= rowspan %>">
     <%= product.maker.name %>
  </th>
  <td rowspan="<%= rowspan %>">
    <%= link_to product.name, product_path(product.id) %>
  </td>
  <% product.product_details.each_with_index do |detail, i| %>
    <td><%= detail.sale_date.strftime("%Y年%m月") %></td>
    <td><%= detail.net_weight %></td>
    <td><%= detail.price %></td>
    <td><%= detail.priceperweight.truncate(2) %></td>
    <td><%= (i < product.product_details.length - 1) ? (detail.priceperweight / product.product_details[i + 1].priceperweight).truncate(2) : '-' %></td>
    </tr>
  <% end %>
<% end %>
</tbody>
</table>

app/views/products/new.html.erb
    <!--<div class="container">-->
    <!--  <div class="panel panel-default">-->
    <!--    <div class="panel-heading">新規登録フォーム</div>-->
    <!--    <div class="panel-body">-->
<%= form_for @product do |f| %>
  <p>
  <%= f.label :maker_id , "メーカー" %>
  <!--<%= f.text_field :maker %>-->
  <!--<%= f.select :maker, ["ブルボン", "カルビー", "森永製菓"],  :prompt => "選択してください" %>-->
  <%= f.select :maker_id, @makers.map{|m| [m.name, m.id]} %>
  </p>
 
  <p>
  <%= f.label :name , "商品名" %>
  <%= f.text_field :name %>
  </p>
  
  <p>
  <%= f.label :net_weight , "内容量(g)" %>
  <%= f.text_field :net_weight %>
  </p>
  
  <p>
  <%= f.label :price , "価格(円)" %>
  <%= f.text_field :price %>
  </p>
  

  <%= f.submit %>
 
<% end %>
    <!--    </div>-->
    <!--  </div>-->
    <!--</div>-->
    
<br>
<%= link_to "トップページ", root_path %>

    <!--bootstrapで使用するコード-->
    <!--<div class="container">-->
    <!--  <div class="panel panel-default">-->
    <!--    <div class="panel-heading">新規登録フォーム</div>-->
    <!--    <div class="panel-body">-->
    <!--      <form>-->
    <!--        <div class="form-group">-->
    <!--          <label class="control-label">メーカー</label>-->
    <!--          <input class="form-control" type="text">-->
    <!--        </div>-->
    <!--        <button class="btn btn-default">送信</button>-->
    <!--      </form>-->
    <!--    </div>-->
    <!--  </div>-->
    <!--</div>-->

app/views/products/show.html.erb
<div id="curve_chart" style="width: 900px; height: 500px"></div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      ['Year', 'Sales', 'Expenses'],
      ['2004',  1000,      400],
      ['2005',  1170,      460],
      ['2006',  660,       1120],
      ['2007',  1030,      540]
    ]);
    var options = {
      title: 'Company Performance',
      curveType: 'function',
      legend: { position: 'bottom' }
    };
    var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));
    chart.draw(data, options);
  }
</script>